export const GET_MAIN_POSTS_REQUEST = "post/GET_MAIN_POSTS_REQUEST";
export const GET_MAIN_POSTS_SUCCESS = "post/GET_MAIN_POSTS_SUCCESS";
export const GET_MAIN_POSTS_ERROR = "post/GET_MAIN_POSTS_ERROR";

export const ADD_MAIN_POST_REQUEST = "post/ADD_MAIN_POST_REQUEST";
export const ADD_MAIN_POST_SUCCESS = "post/ADD_MAIN_POST_SUCCESS";
export const ADD_MAIN_POST_ERROR = "post/ADD_MAIN_POST_ERROR";

export const DELETE_MAIN_POST_REQUEST = "post/DELETE_MAIN_POST_REQUEST";
export const DELETE_MAIN_POST_SUCCESS = "post/DELETE_MAIN_POST_SUCCESS";
export const DELETE_MAIN_POST_ERROR = "post/DELETE_MAIN_POST_ERROR";
