export const GET_MAIN_CAROUSEL_IMAGES_REQUEST =
  "image/GET_MAIN_CAROUSEL_IMAGE_REQUEST";
export const GET_MAIN_CAROUSEL_IMAGES_SUCCESS =
  "image/GET_MAIN_CAROUSEL_IMAGE_SUCCESS";
export const GET_MAIN_CAROUSEL_IMAGES_ERROR =
  "image/GET_MAIN_CAROUSEL_IMAGE_ERROR";

export const ADD_MAIN_CAROUSEL_IMAGE_REQUEST =
  "image/ADD_MAIN_CAROUSEL_IMAGE_REQUEST";
export const ADD_MAIN_CAROUSEL_IMAGE_SUCCESS =
  "image/ADD_MAIN_CAROUSEL_IMAGE_SUCCESS";
export const ADD_MAIN_CAROUSEL_IMAGE_ERROR =
  "image/ADD_MAIN_CAROUSEL_IMAGE_ERROR";

export const DELETE_MAIN_CAROUSEL_IMAGE_REQUEST =
  "image/DELETE_MAIN_CAROUSEL_IMAGE_REQUEST";
export const DELETE_MAIN_CAROUSEL_IMAGE_SUCCESS =
  "image/DELETE_MAIN_CAROUSEL_IMAGE_SUCCESS";
export const DELETE_MAIN_CAROUSEL_IMAGE_ERROR =
  "image/DELETE_MAIN_CAROUSEL_IMAGE_ERROR";
