export const GET_POSTS_REQUEST = "post/GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "post/GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "post/GET_POSTS_ERROR";

export const ADD_POST_REQUEST = "post/ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "post/ADD_POST_SUCCESS";
export const ADD_POST_ERROR = "post/ADD_POST_ERROR";

export const DELETE_POST_REQUEST = "post/DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "post/DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "post/DELETE_POST_ERROR";
